### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by chinweenie** [chinweenie/My-Recipe#1]
- [ ] Navbar (Donnie)

- [ ] Design recipe model (Winnie)

- [ ] Integrate Google register / log in (Roger)

- [ ] Create page for recipes such as index / show page

- [ ] Search form UI

- [ ] Search algorithms based on filters

- [ ] Shopping list UI 

- [ ] Generate shopping algorithms based on recipes
